#
# Home page translateion for template index.html
#

[whitepaper]
other = "白皮书"

[whitepaper_pdf]
other = "stegos中文白皮书.pdf"

[news]
other = "新闻"

[main_header_title]
other =  "拒绝监视 <br> 拥抱自由!"

[main_header_info]
other = "Stegos通过保护用户的隐私信息<br>免受窥探，保护和授权用户<br>。"

[main_header_form_title]
other = "我们很快就会启动"

[your_email_address]
other = "您的邮箱地址"

[learn_more]
other = "了解更多"

[why_stegos]
other = "为何选择STEGOS?"

[absolutely_private]
other = "绝对的<br>隐私"

[confidential_transactions]
other = "隐私交易和隐私消息"

[stealth_addresses]
other = "隐身地址"

[zero_knowledge_proofs]
other = "零知识证明"

[snowball_our_own]
other = "雪球, 我们独有的<br>部署ValueShuffle的<br>方式"

[unlinkable_and_untraceable]
other = "不可链接性和<br>不可追踪性"

[scalable_and_powerful]
other = "可扩容且<br>功能强大"

[horizontal_scalability]
other = "水平扩展性"

[state_and_transactional]
other = "状态分片和交易<br>分片"

[thousands_of_transactions]
other = "每<br>秒<br>转账数（TPS）上千"

[original_r_and_d]
other = "自主研发，<br>并非是分叉"

[fast_and_compact]
other = "快速且<br>紧凑"

[transaction_confirmation]
other = "几秒内即可确认<br>交易<br>"

[old_data_and_transactions]
other = "以前的数据和<br>交易<br>会安全删除"

[small_enough_to_fit]
other = "足够小可以在移动设备上兼容<br>"

[mobile_all_the_way]
other = "专为所有人设计"

[run_a_full_blockchain]
other = "通过手机<br>运行轻<br>节点并通过<br>移动端权益抵押获得代币奖励"

[fair_gamified]
other = "公平的赌注权益证明让<br>你尽管不是<br>加密货币巨鲸也能获得很多！"

[no_messing_around]
other = "使用BTC进行原子交换的P2P交易"

[an_incredibly_easy]
other = "一种非常简单且安全的发送付款和邮件的方式"

[the_stegos_app_integrates]
other = "Stegos app集成了简单易用的消息功能，强大且不受监控"

[create_custom_airdrops]
other = "使用红包给使用二维码的人发送惊喜礼物或进行隐私付款。公共红包和群组红包还可以定制随机奖品用于游戏和促销"

[a_secure_mobile_vm]
other = "运行节点并通过赌注权益证明或验证网络来获得STG代币。验证者服务奖池给予每个人一个公平的机会，无论他们的赌注是多少"

[run_a_node_on_the_smartphone]
other = "使用加密的链式消息传递，提供完全隐私的点对点和群聊，以保证您的会话免受窥探"

[watch_video]
other = "观看视频"

[more_news]
other = "更多新闻"

[the_project]
other = "项目介绍"

[source_code]
other = "源代码"

[community]
other = "社区"

[team]
other = "团队成员"

[roadmap]
other = "路线图"

[mainnet_and_native_token]
other = "主网和原生代币<br> 桌面级钱包"

[exchange_sale]
other = "社区建设和上线交易所"

[sharding]
other = "链上P2P交易和红包"

[mobile_staking]
other = "轻节点和赌注池支持, 移动钱包"

[app_store_private]
other = "分片和无需引导节点的情况下进行区块链删减"

[pruning_with_no_bootstrap]
other = "加入稳定币算法功能"

[partners]
other = "合作伙伴"

[subscribe_to_our_newsletter]
other = "订阅我们的最新信息"

[subscribe]
other = "订阅"

[join]
other = "加入"

[still_have_questions]
other = "还有疑问？"

[join_our_community]
other = "加入我们的社交网络来获得答案"

[back_to_news]
other = "回到新闻"

[next]
other = "下一篇"

[previous]
other = "上一篇"

[stegos_app]
other = "Stegos应用"

[home_title]
other = "拒绝监控 — 拥抱自由!"

[home_description]
other = "Stegos隐私平台结合了独特的区块链和通证设计，是首个实现了完全隐私，安全，高效和环境可持续的加密货币。"

[team_title]
other = "领导层 - 区块链团队 | Stegos"

[team_description]
other = "拥有丰富的区块链经验，拥有金融，航空航天和密码学背景。"

[news_title]
other = "Stegos隐私平台新闻"

[news_description]
other = "有关Stegos隐私平台的新闻"
